version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
      - docker build -t 2donny/4oclock-frontend ./
      - docker push 2donny/4oclock-frontend

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./
