version: '3'
services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '80:3000'
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
