[build.environment]
  NPM_VERSION = "6.14.15"
  NODE_ENV = "production"

[build]
  command = "CI= npm run build"
  publish = "build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=60
    '''
